spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
jwt.secret=b19oCWGaLoNU/+zfEIE0iVRjUK9viIISWYuZAk704hQ=

stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.api.key=${STRIPE_API_KEY}
stripe.price.standard=${STRIPE_PRICE_STANDARD}
stripe.price.night=${STRIPE_PRICE_NIGHT}

resend.api.key=re_TE8in4w7_Q7wBmuAq8XYK9Z8BrZvKcgaV
admin.password=${ADMIN_PASSWORD}
google.client.email=${GOOGLE_CLIENT_EMAIL}
google.private.key=${GOOGLE_PRIVATE_KEY}
google.calendar.id=${GOOGLE_CALENDAR_ID}
